name: sunday_get_storage
description: A fast, extra light and synchronous key-value storage written entirely in Dart
version: 2.1.1
homepage: https://github.com/sunday-team/sunday_get_storage

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  #platform_info: ^3.0.0-nullsafety.1
  file: ^7.0.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter